version: "3.8"
services:
  mongo:
    image: mongo
    volumes:
      - ./mongo-entrypoint:/docker-entrypoint-initdb.d:ro
      - ./data:/data/db
    container_name: mongodb-mern-video-app
    restart: unless-stopped
    ports:
      - 27017:27017
    env_file:
      - ./.env
    command: mongod
